### ISSUE TITLE
Include 1.19.2 on modrinth page

### ISSUE THREAD

**Issue by dlfnn** [xTracr/RealCamera#1]
The existing 1.18.2 version of your mod works perfectly on 1.19.2 (haven't encontered any problems yet)

**Comment by xTracr** [comment]
Is it on Fabric? It seems that on 1.19.2, my mod's config screen is not working properly with `cloth config`  
Though this is the only problem I've found

**Comment by dlfnn** [comment]
Yes it is on fabric. The config gui doesn't work properly, but editing the file works perfect
