### ISSUE TITLE
Other players are headless.

### ISSUE THREAD

**Issue by Landrozaum** [xTracr/RealCamera#10]
In 1.19.4 mod [ realcamera-1.19.4-fabric-0.5.2-beta.jar ] when i disable rendering it disable for all players that im seeing, so if i disable for example heads, all players will be headless.

**Comment by xTracr** [comment]
I tested carpet, multiplayer and server and didnt find the issue you mentioned. Can you provide more information?  
![2023-06-03 173614](https://github.com/xTracr/RealCamera/assets/57320980/8aa095a4-9d32-4c63-abc6-c83f1ca947d2)
By the way, 0.5.1-beta has the issue you mentioned.

**Comment by Landrozaum** [comment]
oh, ok

**Comment by Landrozaum** [comment]
i was using an outdated version
