### ISSUE TITLE
Weird visual glitches with the CPM mod

### ISSUE THREAD

**Issue by Blergonos** [xTracr/RealCamera#11]
Self explanatory. When I use the mod with custom animations the model of the player phases in front of you and looks very weird. Basically unplayable. I don't know if this is fixable because its a custom animation but if it is fixable that would be nice.

https://youtu.be/xvHTAhECw1I
This is a link to the animation file that CPM utilizes.

![2023-06-07_15 44 49](https://github.com/xTracr/RealCamera/assets/129961843/93331680-0056-4e8c-83d5-4ddc476c2b0a)
![2023-06-07_15 44 52](https://github.com/xTracr/RealCamera/assets/129961843/75e5e612-dd35-4d37-836e-b8575e787fd7)
![2023-06-07_15 45 03](https://github.com/xTracr/RealCamera/assets/129961843/1f7d2158-dc65-44cb-8fbb-62f29c6ad7a0)
![2023-06-07_15 45 04](https://github.com/xTracr/RealCamera/assets/129961843/7de5089b-49e6-45f6-bfb6-351b2bfd0cb9)
![2023-06-07_15 45 06](https://github.com/xTracr/RealCamera/assets/129961843/2474b2d1-fa30-4343-b483-ee6e200a0f07)
![2023-06-07_15 45 07](https://github.com/xTracr/RealCamera/assets/129961843/809b4091-8536-4a07-a84b-da02ee2b0b72)

And some images.

**Comment by Blergonos** [comment]
I reopened because yesterday i closed this thinking i fixed the issue becuase of a issue similar to this one being posted some time ago. It was a setting in the mod config which helped, but there are still some bugs so i need more help

**Comment by xTracr** [comment]
Solving this issue is quite complex and is better left to the authors of CPM currently.

**Comment by Blergonos** [comment]
> For Real Camera, solving this issue is quite complex and is better left to the authors of CPM currently.

ok then. sorry for replying 200 years later lol.
