### ISSUE TITLE
Hand visible while playermodel is visible?

### ISSUE THREAD

**Issue by RomoE** [xTracr/RealCamera#13]
As shown, in first person my hand just suddenly began to show up and refuses to disappear, regardless of what tool is being held or empty handed. Works fine with default view

Don't currently have anything installed like first person model, eating animations etc.
![2023-06-12_04 09 47](https://github.com/xTracr/RealCamera/assets/8780385/30c2d15f-824c-4973-a4db-a7eec39c3120)
![2023-06-12_04 09 49](https://github.com/xTracr/RealCamera/assets/8780385/0e521ee1-f93b-4e10-b5d1-05f8677deaac)
![2023-06-12_04 11 26](https://github.com/xTracr/RealCamera/assets/8780385/67cc4510-9071-4dde-bb66-8934928e92f1)

**Comment by xTracr** [comment]
Could you show me your mod list and your `realcamera.json` file in the config folder?
