### ISSUE TITLE
[Suggestion] "Disable in inventory" switch option in the 'disable this mod when' tab

### ISSUE THREAD

**Issue by owosoup** [xTracr/RealCamera#15]
I'm using an animation pack that has an 'inspect' anim where you lean in when opening an inventory (chests, boats, and even your own inventory). My character leans in so I see it even in first person, and that breaks immersion a lot.
Is it possible to disable the mod when using an inventory screen?

**Comment by xTracr** [comment]
Ok, I will add that feature.
