### ISSUE TITLE
crashing upon launch

### ISSUE THREAD

**Issue by Sp-ll** [xTracr/RealCamera#16]
I add the mod through curseforge, and it crashes in the minecraft launcher. The only mods i have are cloth config and RealCamera.

**Comment by xTracr** [comment]
I need more information. Can you show me your crash report or game log file?

**Comment by QuantumMicrowave** [comment]
I'm having the same issue, and it seems to only happen on the 1.19.2 forge version of the mod. The only mods I had were the two listed as well as optifine and lazyDFU. 
Here is the crash report:
[crash-2023-07-02_01.32.58-fml.txt](https://github.com/xTracr/RealCamera/files/11928758/crash-2023-07-02_01.32.58-fml.txt)

**Comment by xTracr** [comment]
This mod is incompatible with Optifine and I'm not going to fix it.  
I should have written this in a more visible place.
