### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by supershorty1** [xTracr/RealCamera#17]
[1.webm](https://github.com/xTracr/RealCamera/assets/111652379/a8c81865-8103-4130-836d-9ea21af8e1a1)
![FTIVP3_$OI}XIJZDXS2$960](https://github.com/xTracr/RealCamera/assets/111652379/b566f2e8-9aad-4af4-89d6-cc6bf0eef657)

**Comment by xTracr** [comment]
看你游戏内是中文，那我就用中文好了~~下面这么长要用英文着实有点困难~~  

啊...这个问题非常麻烦~~可能只是对我而言~~，我最开始就注意到它了，但也不知道怎么比较完美地解决。只能尽量规避一下了吧，或者在配置界面加入一个切换计算方式的选项？  

我解释一下吧，尽管不知道能不能让人看懂：  
模型的姿态在计算过程中是以矩阵（三阶方阵）的形式记录的[^1]，而摄像头只具有俯仰角和偏航角（原版没有摄像头翻滚），所以要把模型的姿态转化为摄像头的俯仰角和偏航角，必须从旋转矩阵中提取出欧拉角。
但是三维空间的旋转矩阵与欧拉角并不一一对应（应该是一对二？6种旋转顺序，12种提取公式），这在完整使用了三个角的情况下没有问题，但是如果要取消绑定其中的一个或数个角，就可能出现问题，因为不知道实际上玩家需要的是那种效果。
以俯仰135度（绕图中X轴正方向旋转135度）为例，
![示例](https://github.com/xTracr/RealCamera/assets/57320980/961dad8a-af14-4efa-a92c-be8ba06971bd)
![矩阵计算](https://github.com/xTracr/RealCamera/assets/57320980/f22ce2af-4597-4d52-8228-dd6b4710bbc0)
根据计算，或者在脑子里想象一下，上图中两种旋转方式结果上是一样的（注意翻滚->俯仰->偏航的旋转顺序），这两种旋转方式也对应了两种提取公式。但是禁用了这三个角中的一项或数项，结果就不一样了。问题是，经过了大量对模型的操作之后，程序中应该是无法得知应该选用哪种提取公式符合玩家的预期。  

你给出的这种情况，应该是刚好是另一个提取公式更合适（实际上这应该也是大多数情况吧，但是这个公式相比于我现在用的，没有那么直接，比较麻烦）。  

[^1]:具体地讲，是在计算其在屏幕中显示的姿态和位置时，用矩阵栈`MatrixStack`（使用Yarn映射时；使用官方映射则是姿态栈`PoseStack`）记录的，它以栈的形式存储了多组矩阵，每组矩阵包含一个三阶方阵旋转矩阵和一个四阶方阵位置矩阵。计算过程中程序会把对模型的每一项操作，比如相对某轴旋转45度，转化为矩阵的运算，最后再根据栈顶的那组矩阵算出模型的每一个点相对摄像头的位置和每个平面的法向量相对摄像头的方向。

**Comment by supershorty1** [comment]
我的数学不太理想，不过这个现象应该和万向锁类似？总之感谢你的耐心回复。

**Comment by xTracr** [comment]
虽然都是与欧拉角相关的，但是不太一样。万向角的问题应该是已经被规避了。
再简短一点的话，就是有两种结果一样但过程不一样的算法A和B，我采用了算法A，本来没有问题，但是取消绑定几个角度，过程的分歧就出现了，而你这种恰好是与算法B的中间结果相吻合，而与算法A不吻合。

**Comment by supershorty1** [comment]
> 虽然都是与欧拉角相关的，但是不太一样。万向角的问题应该是已经被规避了。 再简短一点的话，就是有两种结果一样但过程不一样的算法A和B，我采用了算法A，本来没有问题，但是取消绑定几个角度，过程的分歧就出现了，而你这种恰好是与算法B的中间结果相吻合，而与算法A不吻合。

能否使滚转角度随着俯仰角度变大而减小，或者至少防止其超过一个角度？

**Comment by xTracr** [comment]
可以是可以，就是用另一个算法就行，但是对于滚转角超过180度的情况就又不行了，虽然这种情况很少，几乎只在鞘翅飞行时出现。  
> 你给出的这种情况，应该是刚好是另一个提取公式更合适（实际上这应该也是大多数情况吧，但是这个公式相比于我现在用的，没有那么直接，比较麻烦）。
