### ISSUE TITLE
It would be really really cool if the head model could be hidden while using the RealCamera perspective!

### ISSUE THREAD

**Issue by dlfnn** [xTracr/RealCamera#2]
This mod is already really cool by how it is, so no pressure at all! I just feels like though it could be made better:

So currently the camera is best to be bound at the player's face, but when you look down it can clip through their body
![}LDOAB@ R1V(H`{E`P32DR1](https://user-images.githubusercontent.com/94152497/234591440-ff004b7d-36ff-4f26-92a0-f1222396c569.jpg)

But if the head model is hidden, the camera can be placed at an arguably more reasonable place like so:
![2`2O{R$ P}`1TX~_ER3RVX0](https://user-images.githubusercontent.com/94152497/234592056-34a1be6d-6df4-4738-937e-9d4418e5ee76.png)

Still, thank you for this cool mod!

**Comment by xTracr** [comment]
You can use 'First-person Model' and disable 'Render Player Model' in my mod's config.   
If I have some spare time one day, I may consider adding it as a default disabled feature.(Actually, I've tried it before, but it's quite complicated to perfect)

**Comment by dlfnn** [comment]
doesn't work as intended though. in defaut first person perspective it has `First-person Model`'s model and its camera (located in the center of player head), while on RealCamera perspective it has the right camera but no model is rendered.
Thanks anyway, good luck when you have time!

**Comment by xTracr** [comment]
Have you checked for key conflicts? The default `Toggle Firstperson` key and my `Toggle Camera` key conflict with each other.  Based on my tests, it is possible to use `First-person Model` and my camera perspective together. And changing the config of 'First-person Model' to `xOffset`=-25,`sneakXOffset`=-27 and `sitXOffset`=-20 seems best.  
However, as in the following image, these two is not working together as well as I had imagined, so maybe I should consider adding this feature now.
![Screenshots 2023-04-27 101617](https://user-images.githubusercontent.com/57320980/234745623-0fd80bde-9447-4b7c-99c1-f1fd00a5b6f9.png)

**Comment by dlfnn** [comment]
Oh! It actually works pretty perfectly! What is needed is to set the X offset in `First-Person Model` to -20 so that its camera would anchor to the center, and then adjust the offset for your mod. 
Thank you so much for this!
