### ISSUE TITLE
limit certain axis rotation of the camera（摄像机限制特定轴向运动）

### ISSUE THREAD

**Issue by supershorty1** [xTracr/RealCamera#3]
如果可能的话，添加摄像机限制特定轴向运动的功能可以减少一些让人感觉奇怪或者眩晕的地方（游泳的时候前进方向和摄像头方向不一致，趴下无法向上看等）。请务必考虑，十分感谢。

**Comment by xTracr** [comment]
只能限制翻滚，大概可以稍微减少一点眩晕吧  
<img decoding="async" src="https://github.com/xTracr/RealCamera/assets/57320980/b682f2dc-9a4e-4007-888d-db0e5e4758a9" width="60%">  
但是游泳前进方向和摄像头方向不一致，趴下无法向上看都是模型动作的原因: 游泳的时候头就是和前进方向有45度夹角的，趴下时头部也不能向上转动  
本模组并不打算涉及模型本身或动作的修改，所以就只能在这些情况下禁用了。
<img decoding="async" src="https://github.com/xTracr/RealCamera/assets/57320980/95686a6a-0edd-41b6-a249-f454907ff635" width="60%">

**Comment by supershorty1** [comment]
> 好的，十分感谢

**Comment by supershorty1** [comment]
> 只能限制翻滚，大概可以稍微减少一点眩晕吧 <img alt="" width="60%" src="https://user-images.githubusercontent.com/57320980/239432362-b682f2dc-9a4e-4007-888d-db0e5e4758a9.png"> 但是游泳前进方向和摄像头方向不一致，趴下无法向上看都是模型动作的原因: 游泳的时候头就是和前进方向有45度夹角的，趴下时头部也不能向上转动 本模组并不打算涉及模型本身或动作的修改，所以就只能在这些情况下禁用了。 <img alt="" width="60%" src="https://user-images.githubusercontent.com/57320980/239432777-95686a6a-0edd-41b6-a249-f454907ff635.png">

请问有可能实现只取消绑定带来的额外俯仰，只保留翻滚吗

**Comment by xTracr** [comment]
可以，还挺容易的  
我确实应该去做一下，分别给这三个做一个选项

**Comment by supershorty1** [comment]
> 

十分感谢

**Comment by supershorty1** [comment]
貌似在最新版中这个功能没有作用了

**Comment by xTracr** [comment]
啊，是forge版的问题吗，应该是我忘了在forge的event那里面写判断了

**Comment by xTracr** [comment]
嘛，总之我先把modrinth上的重新上传了，curseforge没法直接改文件暂时没弄，你可以到modrinth上下下来看看有没有修好

**Comment by supershorty1** [comment]
好了，感谢
