### ISSUE TITLE
Real Camera disables itself when climbing a ladder when prevent block clipping is enabled [1.19.2 Forge 43.3.2].

### ISSUE THREAD

**Issue by Quartofel** [xTracr/RealCamera#37]
As title says.
When climbing a ladder, vanilla first person activates. My guess is that it's the way of preventing clipping, but it's very jarring, and when clipping prevention is disabled, model doesn't clip anyway.

PS.: Would it be possible to have some other way of clip prevention in the future rather than just falling back to vanilla first person? This mod does wonders for immersion, and having suddenly disembodied broken arm right in my face is extra jarring due to how well it works rest of the time.

**Comment by xTracr** [comment]
It's a troublesome problem and it may take me a long time to have a better solution (honestly, I've been playing other games for the past 6 months, so there hasn't been much progress). 
At the present time, the difference between 0.5.4 and 0.5.3 is pretty small, you can try which one suits you better. ~~Or if havent tried before, you can try *First Person Model*, a more complete mod.~~

On a more basical level, it's a problem of models (especially head and when swimming) often going outside the hitting box.

**Comment by Quartofel** [comment]
I'm using First Person Model, but I keep returning to this project every couple of months to see if I can switch for long-term playing :P

I overall think that your mod handles motion the "realest" out of the two and when it works, it works great (with Parcool! for example), but then again, there are rough patches that break the immersion (clipping prevention for instance).

Best of luck and thank you for your mod!

**Comment by xTracr** [comment]
The clipping issue should have been greatly improved in 0.5.5 because just a few days after I had replied to you, I came up with a good idea. 
You could try it again now.
