### ISSUE TITLE
Animations Are Weird

### ISSUE THREAD

**Issue by LordEnder-Kitty** [xTracr/RealCamera#4]
The models animations are really weird in first person. they either don't play or are moving but just barely. im not sure if another mod of mine is incompatible with it but i just thought i should put it out there. 

here's my latest.log file after testing the mod out if it helps.
[latest.log](https://github.com/xTracr/RealCamera/files/11605300/latest.log)

**Comment by xTracr** [comment]
Have you installed resource packages that depend on `Entity Model Features`?

**Comment by Shad0wolf0** [comment]
I feel like I have the same problem. I'm tested with the First person model mod and by comparing it to RealCamera, it seems that RealCamera is more softer compared to FPM. I also have EMF installed without any resource pack

**Comment by xTracr** [comment]
I guess I know where the problem is.  
Disabling ‘Animation Smoothing’ in the config screen of Not Enough Animations can solve this issue.

**Comment by Shad0wolf0** [comment]
It worked as I also have NotEnoughAnimations.
