### ISSUE TITLE
Mod crashes with slot_head enabled

### ISSUE THREAD

**Issue by GabeXx546** [xTracr/RealCamera#41]
When loading into a world, the game crashes when I have slot_head enabled. It doesn't happen with head or helmet. The world loads to 100% then crashes. No way around this either since without having slot_head enabled, anything on my head is now always in my vision. Most likely a conflicting mod but I don't know what it would be

**Comment by xTracr** [comment]
I need more information. Can you show me your crash report or game log file?

**Comment by GabeXx546** [comment]
Here is the crashlog found in the crash reports folder
[crash-2023-12-24_14.45.02-client.txt](https://github.com/xTracr/RealCamera/files/13762693/crash-2023-12-24_14.45.02-client.txt)
Here is the log from the modrinth launcher
https://mclo.gs/SUgIvOj

**Comment by Plasman888** [comment]
I still encounter this issue
