### ISSUE TITLE
视角变换开关

### ISSUE THREAD

**Issue by moyuguguji** [xTracr/RealCamera#45]
请问一下能否仅渲染而不变换视角,bettercombat动作攻速太快的话会很晕

**Comment by xTracr** [comment]
你可以试试把绑定模式里的“偏移模型”打开，“摄像头旋转”里的三个角度的绑定关了，再把头部及相关模型的渲染禁用。 
但是这样的话，感觉跟隔壁~First-person Model~差不多了。 
当然，上面这些你可以只做一部分看看效果如何

**Comment by moyuguguji** [comment]
[minecraft-exported-crash-info-2024-01-17T16-07-38.zip](https://github.com/xTracr/RealCamera/files/13960320/minecraft-exported-crash-info-2024-01-17T16-07-38.zip)
谢谢,效果确实没那么晕了,但是不知道为什么禁用slot_ head就会崩溃,以及禁用hat貌似不生效
[realcamera.json](https://github.com/xTracr/RealCamera/files/13960428/realcamera.json)
zhe配置文件

**Comment by xTracr** [comment]
禁用slot_ head就会崩溃已经修好了，只是还没发布。
hat是头部的外面那层皮肤，也是皮肤的一部分，如果你的皮肤没有第二层或者不明显的话可能就看不出来
