### ISSUE TITLE
Compatible with Parcool mod 1.20.1

### ISSUE THREAD

**Issue by Kogomre** [xTracr/RealCamera#47]
Hello, I want to thank you for such a wonderful, fairly well-developed mod, especially for the excellent support for chairs and other cool things. When using Ctrl acceleration in the Parcool mod, the camera shakes a little when turning, can this be somehow corrected through the mod options? Below is a video of the problem.

https://github.com/xTracr/RealCamera/assets/43267690/3bbf9dab-e7f1-4e38-9353-0bcc96db1731

https://github.com/xTracr/RealCamera/assets/43267690/7d598022-64b8-4c9c-8050-d52dff2f3fc6

Forge 47.2.19
Realcamera-1.20.2-forge-0.5.5-beta.jar
ParCool-1.20.1-3.1.0.6-R.jar

**Comment by xTracr** [comment]
This seems to be an animation issue with Parcool, which can be seen more clearly in third person view.

**Comment by Kogomre** [comment]
Maybe this help someone
https://github.com/alRex-U/ParCool/issues/227

**Comment by xTracr** [comment]
The latest version of Real Camera should not have this issue anymore, as the X, Z and rotation of the camera would not be modified by default
