### ISSUE TITLE
View hidden if your player skin has a front facing "hat" (Fabric 1.19.2 v 0.5.0 & 0.5.1)

### ISSUE THREAD

**Issue by awesomepowner** [xTracr/RealCamera#5]
I was trying to get the mod to work since my view was blocked, but I realized the issue was that my minecraft skin "hat" was placed where the camera is, almost like a mask. I am able to fix it by turning it off in my Minecraft skin settings but I thought its worth mentioning (since the camera is behind it)

**Comment by xTracr** [comment]
Oh, you are using 1.19.2.  
Go to `.\config\realcamera.json` and change the value of `renderModelPart` in category `disable` to `true`.  
This might be better than changing Minecraft skin settings.
