### ISSUE TITLE
settings reset

### ISSUE THREAD

**Issue by minsins** [xTracr/RealCamera#50]
### question
You will need a key to reset the settings

**Comment by xTracr** [comment]
All the reset buttons in the config screen are automatically generated by Cloth Config API, which doesn't seem to provide a button to reset all the settings.  
You can reset the settings by deleting the config file `realcamera.json`.

**Comment by minsins** [comment]
Thank you!

2024년 2월 1일 (목) 오후 12:04, xTracr ***@***.***>님이 작성:
