### ISSUE TITLE
与 Figura 的兼容性问题

### ISSUE THREAD

**Issue by FunnyShadow** [xTracr/RealCamera#57]
我在使用 [Figura](https://modrinth.com/mod/figura) (一个类似于 YSM 的 Mod) 时遇到了如图所示 (目前还没截图...之后会传上来) 的问题，这个皮肤模型有一个类似于刘海的玩意，而图片中糊脸的内容即为这个刘海

这个问题在新版的 First Person Model 上同样出现了 (表现形式有一些差异, 但是效果基本相同)，起初我以为是 Figura 或者我采用的模型的问题，后来我在 Figura 开发团队的指导下简单修复了一下这个模型，然后给这个模型的仓库提交了 PR，不过经过我和该模型作者的测试发现，这个问题可能来源于 First Person Model 以及 Real Camera 的问题，所以我们俩就给两个 Mod 的仓库都提交了一份 Issue，下面是一些相关 Issue 的链接（我注意到有一个本仓库的 Issue 与我的问题十分相似，也已经一并附在下方了）

我的测试环境与第一个 Issue 中发起人提供的环境是一致的，但 First Person Model 模组被替换成了 Real Camera 最新版~~其实就是懒得重新敲一遍了~~

- 模型仓库的修复 PR：https://github.com/Gakuto1112/SenkoSan/pull/15
- Figura 那边的 Issue：https://github.com/FiguraMC/Figura/issues/195
- First Person Model 那边的 Issue：https://github.com/tr7zw/FirstPersonModel/issues/431
- 本仓库的另外一个 Issue：https://github.com/xTracr/RealCamera/issues/43

**Comment by FunnyShadow** [comment]
![Screenshot_2024-03-05-22-44-16_1920x1080](https://github.com/xTracr/RealCamera/assets/53890138/ebc394d4-63cb-4291-ac5f-3e9df5275995)

顺带一提，我才看到貌似 RealCamera 本身就带一些兼容性选项？我待会儿去试试

**Comment by xTracr** [comment]
在那个模型的预览界面可以把深度（工具提示里有写，就是所有点到屏幕距离都小于该值的面的渲染会被禁用）增大，这个深度就是为了禁用面前的挡视野的东西而写的
另外，0.6的绑定的实现非常底层，通常都是兼容的，以前的兼容选项都无效了，所以在alpha.4里已经被我删光了

**Comment by FunnyShadow** [comment]
好的，我会再去试试，十分感谢
