### ISSUE TITLE
Conflict with Physics Mod Pro ocean physics

### ISSUE THREAD

**Issue by SkyTheNerd** [xTracr/RealCamera#6]
Ocean physics causes the player model and camera to move up and down, to work with the waves, which causes two conflicts because the camera will not move with the player model when this happens.

[Issue 1: Player moving with waves while the camera doesn't](https://cdn.discordapp.com/attachments/867367450022379520/1113462887772594306/2023-05-31_09-34-38.mp4)

[Issue 2: Because the camera isn't moving, it follows the vanilla water plane.](https://cdn.discordapp.com/attachments/867367450022379520/1113462989358649434/2023-05-31_09-44-19.mp4)

Physics Mod Pro is now free, which means you can download it from [here](https://ko-fi.com/post/Physics-Mod-Pro-V154--Liquid-Physics-V2-H2H1LJYDG)

**Comment by xTracr** [comment]
Physics is a closed source mod, so it's a bit troublesome to fix.  
Anyway, I will try to fix it.
