### ISSUE TITLE
First Person is buggy when in dungeon by Dungeonz mod 

### ISSUE THREAD

**Issue by NotTheRealRoKur0** [xTracr/RealCamera#60]
for some reason, when I enter a dungeon (from: [DungeonZ](https://github.com/Globox1997/DungeonZ)), my First Person goes glitchy and the camera is in my head again.
[realcamera-0.6.0-alpha.1]

video showcasing the problem:
https://drive.google.com/file/d/1Cu9dSi9xK29uo8eLwT3Qem1BYtxVLqNr/view?usp=sharing

⁣

(_**has nothing to do with the problem above**_)
also  in the newest version (also tested the newest snapshot) the first person model only shows when a better combat animation plays. (tested it without my modpack and it worked)
may be a performance mod breaking this?

**Comment by xTracr** [comment]
The issue above has just been fixed  
but I have no idea about the issue below, I need more information, such as the game log to reproduce it

**Comment by NotTheRealRoKur0** [comment]
I'll try to find the mod thats causing the issues.
If I find it I'll reopen

**Comment by NotTheRealRoKur0** [comment]
ok I got it, it's [3D Skin Layers](https://modrinth.com/mod/3dskinlayers) [v.1.6.2]
it completely disables the first person model

using [realcamera-0.6.0-beta (latest snapshot)]


but for some reason when [Emotecraft](https://modrinth.com/mod/emotecraft) is enabled the First Person Model gets rendered when attacking with Better Combat,
but when disabled its not rendered entirely again

**Comment by xTracr** [comment]
[snapshot](https://github.com/xTracr/RealCamera/actions/runs/8214748640)
