### ISSUE TITLE
Real Camera and Better Combat Compatibility Issues

### ISSUE THREAD

**Issue by Jackose** [xTracr/RealCamera#61]
Game Version: Fabric 1.20.1

Mods:
- Better Combat (1.8.4)
- Cloth Config API
- Fabric API
- Mod Menu
- Player Animator
- Real Camera

Basically the camera won't follow the tilt of the player's head when going through Better Combat animations. The camera behaves how it would without Better Combat. The visible player model works fine except for this:
![2024-03-10_07 27 24](https://github.com/xTracr/RealCamera/assets/88597667/ba30465c-652c-40c6-bd6f-e44a8c14e5ec)
Two swords?

I've messed with the config settings of both mods but can't figure out how to fix this. I'm also not sure how to have swimming like in description. Maybe these just aren't for this version :(

**Comment by Jackose** [comment]
Huh that's _odd_. Turns out all of these issue are specific to 0.6. Everything works fine on 0.5.5. Well yay but I still hope these things get fixed eventually.

**Comment by xTracr** [comment]
duplicate?
#59

**Comment by Jackose** [comment]
:P
