### ISSUE TITLE
Incompatibility with Physics Mod and Sinytra Connector [1.20.1]

### ISSUE THREAD

**Issue by BoardAnims** [xTracr/RealCamera#63]
#56 fixed incompatibility with Physics Mod and Real Camera.
However, having Sinytra Connector, Physics Mod and Real Camera together will cause a crash whenever the "real camera" is toggled on.

[latest.log](https://github.com/xTracr/RealCamera/files/14576360/latest.log)
[crash-2024-03-12_18.15.33-client.txt](https://github.com/xTracr/RealCamera/files/14576410/crash-2024-03-12_18.15.33-client.txt)

**Comment by xTracr** [comment]
The version of Real Camera you installed is 0.6.0-alpha.1  
You should first update to the latest version

**Comment by BoardAnims** [comment]
You're right, 0.6.0-beta doesn't crash for me.
My fault for not updating mods :/

**Comment by BoardAnims** [comment]
> The version of Real Camera you installed is 0.6.0-alpha.1 You should first update to the latest version

Wait, why were the "Disable Settings" removed in the 0.6.0-alpha.4? Those disablers made it actually possible to use a map and spyglass.
