### ISSUE TITLE
Cannot bound to MCAR player (villager) model

### ISSUE THREAD

**Issue by KinokoSoft** [xTracr/RealCamera#85]
> ### 环境：
> - Minecraft 1.20.1
> - Quilt Loader 0.26.4
> - Real Camera 0.6.1-beta
> - mca 7.5.18+1.20.1

玩家在使用 Minecraft Comes Alive Reborn 的村民模型时尝试使用 Real Camera 绑定模式时，Preview 界面无法看见相机位置，在游戏中尝试切换 RealCamera 会提示绑定失败 `[Real Camera]: Binding failed, please go to the Model View screen and configure manually`.  
（我不确定是不是我自己不清楚如何正确使用绑定菜单导致的）

![image](https://github.com/xTracr/RealCamera/assets/171643904/567b7902-258f-45a7-bd5f-26e361a832ae)

![image](https://github.com/xTracr/RealCamera/assets/171643904/b056b767-71b1-4abb-bbab-bc8623ff6e67)

**Comment by xTracr** [comment]
>  By clicking the `Selecting` button on the left, switch between the three to select the `Forward Vector`, `Upward Vector`, and `Target Plane`
> 通过点击左侧的`选择`按钮，在三者间切换，选好`向前矢量`、`向上矢量`和`目标平面`
要选三次才能正确绑定

**Comment by Kirisoup** [comment]
> > By clicking the `Selecting` button on the left, switch between the three to select the `Forward Vector`, `Upward Vector`, and `Target Plane`
> > 通过点击左侧的`选择`按钮，在三者间切换，选好`向前矢量`、`向上矢量`和`目标平面`
> 
> 要选三次才能正确绑定

感谢感谢。是我笨蛋了，抱歉
