### ISSUE TITLE
Binding failed, please go to the Model View screen and configure manually

### ISSUE THREAD

**Issue by ZigzOz** [xTracr/RealCamera#86]
"Binding failed, please go to the Model View screen and configure manually", I did but nothing works. tried pressing f6 and it doesn't work either

**Comment by xTracr** [comment]
So did you go to the Model View screen?  
I need more information, like this one #85

**Comment by ZigzOz** [comment]
Okay, i just restarted it a few times and if fixed

**Comment by ZigzOz** [comment]
Nvm it just started not working again

**Comment by xTracr** [comment]
> * Theoretically, most mod models are supported, but need to be configured manually:
> * First, set the key binding for `Open Model View Screen`.
>   * ![model view screen](https://cdn.modrinth.com/data/fYYSAh4R/images/cc484d54238992077ab3632c274a2631efeca35f.png)
> * Open the model view screen and left click with left Alt held to select the corresponding face of the model, scroll with left Alt held to switch between the different layers of the model.
> * By clicking the `Selecting` button on the left, switch between the three to select the `Forward Vector`, `Upward Vector`, and `Target Plane`.
> * Enter the `Preview` section, where you can see the relative relationship between the camera and the model and make certain adjustments (you can also adjust through key bindings).
>   * ![preview](https://cdn.modrinth.com/data/fYYSAh4R/images/22cfcf444bbf2d3c0d0280e470a29f01b9308617.png)
> * Enter a name and save (if needed, other settings such as priority can be changed).

**Comment by ZigzOz** [comment]
Thanks, I tried to change the skin location and it started working when there was nothig in the skin location window.
