### ISSUE TITLE
[Bug] Exposure camera item in hand obscures view.

### ISSUE THREAD

**Issue by NovaLynxie** [xTracr/RealCamera#88]
Hi there, I have noticed a strange bug which causes the exposure camera item to be rendered in the player view, and the item in hand blocks the camera's reticle POV in that mod. I am unsure if it is related to #69, which was opened some time ago but has since been marked as resolved. Using spyglasses, which render a similar view, shows this working normally, which is what I would expect it to do.

![image](https://github.com/xTracr/RealCamera/assets/21307676/65f64b44-ba47-4d11-9a77-98de05d54aff)

Steps to reproduce
1. Install Real Camera and Exposure.
2. Open any world or create a new world.
3. Obtain the camera item.
4. Attempt to use the camera to take a picture with render player model in first person enabled.

Expected:
Use a camera that renders like the spyglass POV without any item in the frame.
Actual:
Hand and camera items are rendered in first-person view, which blocks the camera frame.

Because of this, I have to toggle the player rendering off in the settings or temporarily disable the real camera's perspective while I use the camera. This isn't ideal. Can this be fixed? Thanks.

Mods used:
Forge 42.2.20 for Minecraft 1.20.1
Real Camera v0.6.1-beta
Exposure 1.6.0

**Comment by xTracr** [comment]
![screenshot 2024-07-02 123305](https://github.com/xTracr/RealCamera/assets/57320980/4b93adff-6638-4131-9e1f-341d294537f9)

**Comment by NovaLynxie** [comment]
Hey, so this is an update since the issue was closed: I addressed this with the exposure mod's author, and it has been patched on their end. Referenced issue: https://github.com/mortuusars/Exposure/issues/100
Updating that mod to v1.7.3 fixes this problem. Adding this here in case anyone happens to be using these two mods together.
