### ISSUE TITLE
A few compatibility issues

### ISSUE THREAD

**Issue by Aceplante2** [xTracr/RealCamera#9]
I have better first person, pehkui, and 3d skin layer.

When I look down my vision is inside my player model?

I can also see through the outer layer of my skin. I would expect vision to be blocked by it.

I am using forge 1.18.2

**Comment by xTracr** [comment]
This should not be a compatibility issue.  
In the default config, the camera will be just at the player's eyes, and sometimes your vision will indeed be inside the model, which is also mentioned in #2.  
You can now disable the rendering of model parts in the config and then adjust the camera offset to solve the problem.

**Comment by Aceplante2** [comment]
I cant figure it out, ive been messing with the config and it doesnt seem to change anything. Which one should I change if, when i look down, my eyes are in my player model

**Comment by xTracr** [comment]
![2023-06-03 161722](https://github.com/xTracr/RealCamera/assets/57320980/f7dfdfaa-dd97-4403-97cd-bcd794827744)  
And  
![2023-06-03 161741](https://github.com/xTracr/RealCamera/assets/57320980/34b15c41-83e8-4a0a-ac42-b2b3b0b38ffb)

**Comment by Aceplante2** [comment]
Ah, that worked, thank you. The only issue now is I can see inside my model if I turn quickly, although I'm not sure if that can be prevented.

**Comment by xTracr** [comment]
You can try more to adjust the camera offset with hotkeys.  
If there is no more problem then I will close this issue, otherwise please tell me the details.
